apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-deplo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-deplo
  template:
    metadata:
      labels:
        app: springboot-deplo
    spec:
      imagePullSecrets:
      - name: masterkey
      containers:
      - name: springboot-deplo
        image: master:9001/demo:1
        ports:
        - containerPort: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: springboot-svc
spec:
  type: NodePort
  selector:
    app: springboot-deplo
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
      nodePort: 32000