apiVersion: apps/v1
kind: Pod
metadata:
  name: demo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: demo
        image: 192.168.149.141:9001/demo:1
        ports:
        - containerPort: 9090


        